version: 0.2
# Based on the Docker documentation, must include the DOCKER_CLI_EXPERIMENTAL environment variable
# https://docs.docker.com/engine/reference/commandline/manifest/    

phases:
    install:
        commands:
            - yum update -y
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker manifest...   
            - export DOCKER_CLI_EXPERIMENTAL=enabled       
            - docker manifest create public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME:latest-arm64v8 public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME:latest-amd64    
            - docker manifest annotate --arch arm64 public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME:latest-arm64v8
            - docker manifest annotate --arch amd64 public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME:latest-amd64

    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker manifest push public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME
            - docker manifest inspect public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME
