version: 0.2
env:
    secrets-manager:
        DOCKERHUB_USER: arn:aws:secretsmanager:ap-northeast-1:092507187565:secret:Docker-MOP44l:username
        DOCKERHUB_PASS: arn:aws:secretsmanager:ap-northeast-1:092507187565:secret:Docker-MOP44l:password
phases:
    install:
        commands:
            - yum update -y
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h3b4x6x6
            # Docker Hub へのログイン
            - echo Logging in to Docker Hub...
            - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...
            - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME:$IMAGE_TAG
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME:latest
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push public.ecr.aws/h3b4x6x6/$IMAGE_REPO_NAME:$IMAGE_TAG
